[package]
name = "rust"
version = "0.2.0"
authors = ["Michael Gerhaeuser <michael.gerhaeuser@gmail.com>", "rrokkam <rohithrokkam@gmail.com>"]
edition = "2018"

[dependencies]
rstest = "0.11.0"
speculate = "0.1.2"
